import secrets
from datetime import date, datetime

from sqlalchemy import JSON, Date, DateTime, Float, ForeignKey, Integer, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base


def _short_id() -> str:
    return secrets.token_hex(4)


class Entreprise(Base):
    __tablename__ = "entreprises"

    id: Mapped[str] = mapped_column(String(16), primary_key=True, default=_short_id)
    segment_id: Mapped[str | None] = mapped_column(
        String(16),
        ForeignKey("segments.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )

    entreprise: Mapped[str] = mapped_column(String, nullable=False, default="")
    site_web: Mapped[str] = mapped_column(String, nullable=False, default="")
    secteur: Mapped[str] = mapped_column(String, nullable=False, default="")
    adresse: Mapped[str] = mapped_column(String, nullable=False, default="")
    code_postal: Mapped[str] = mapped_column(String, nullable=False, default="")
    ville: Mapped[str] = mapped_column(String, nullable=False, default="")
    taille: Mapped[str] = mapped_column(String, nullable=False, default="")
    ca: Mapped[str] = mapped_column(String, nullable=False, default="")
    linkedin: Mapped[str] = mapped_column(String, nullable=False, default="")
    score: Mapped[str] = mapped_column(String, nullable=False, default="")
    origine: Mapped[str] = mapped_column(String, nullable=False, default="")

    # Flat list of short tags (max ~4 words each) — the same shape produced
    # by the sourcer and shown as badges in the candidate card.
    signaux: Mapped[list] = mapped_column(JSON, nullable=False, default=list)
    note: Mapped[str] = mapped_column(Text, nullable=False, default="")

    # Rich HTML fiche generated by Gemini (google_search + thinking) on
    # candidate validation. Read-only at the prospect level (displayed in
    # ProspectSheet via the entreprise relation). Regenerable from the
    # EntrepriseSheet or the fiche-editor agent.
    fiche_client: Mapped[str] = mapped_column(Text, nullable=False, default="")

    # API Entreprise (recherche-entreprises.api.gouv.fr) — structured identity.
    siren: Mapped[str | None] = mapped_column(String(9), nullable=True, index=True)
    siret: Mapped[str | None] = mapped_column(String(14), nullable=True, index=True)
    naf_code: Mapped[str | None] = mapped_column(String(8), nullable=True)
    naf_label: Mapped[str | None] = mapped_column(String, nullable=True)
    effectif: Mapped[str | None] = mapped_column(String, nullable=True)
    date_creation: Mapped[date | None] = mapped_column(Date, nullable=True)
    dirigeants: Mapped[list] = mapped_column(JSON, nullable=False, default=list)

    # Google Places API enrichment — phone, GPS, rating, reviews, Maps URL.
    telephone: Mapped[str] = mapped_column(String, nullable=False, default="")
    google_place_id: Mapped[str] = mapped_column(String, nullable=False, default="")
    google_maps_url: Mapped[str] = mapped_column(String, nullable=False, default="")
    google_rating: Mapped[float | None] = mapped_column(Float, nullable=True)
    google_rating_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    latitude: Mapped[float | None] = mapped_column(Float, nullable=True)
    longitude: Mapped[float | None] = mapped_column(Float, nullable=True)

    # Per-field provenance. Keys are tracked field names; values are
    # FieldSource literals ("api_gouv" | "ai_grounding" | "ai_grounding_verified"
    # | "finess" | "ordre" | "google_places" | "manual" | "gemini").
    field_sources: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    contacts: Mapped[list["Prospect"]] = relationship(  # noqa: F821
        "Prospect",
        back_populates="entreprise",
        cascade="save-update",
        lazy="noload",
    )
